drop table if exists location;
drop table if exists product;
drop table if exists user_table;
drop sequence if exists hibernate_sequence;
create sequence hibernate_sequence start with 1 increment by 1;
create table location
(
    id INT8 GENERATED BY DEFAULT AS IDENTITY,
    location_code integer not null,
    name          varchar(255),
    primary key (id)
);
create table product
(
    id INT8 GENERATED BY DEFAULT AS IDENTITY,
    name         varchar(255),
    price        integer not null,
    primary key (id)
);
create table user_table
(
    id INT8 GENERATED BY DEFAULT AS IDENTITY,
    location varchar(255),
    name     varchar(255),
    primary key (id)
);
