drop table if exists location CASCADE;
drop table if exists product CASCADE;
drop table if exists user_table CASCADE;
-- drop sequence if exists hibernate_sequence;
-- create sequence hibernate_sequence start with 1 increment by 1;

create table location (
                          id bigint generated by default as identity,
                          location_code integer,
                          name varchar(255),
                          primary key (id)
);

create table product (
                         id bigint generated by default as identity,
                         name varchar(255),
                         price integer,
                         user_id bigint,
                         primary key (id)
);

create table user_table (
                            id bigint generated by default as identity,
                            name varchar(255),
                            location_id bigint,
                            primary key (id)
);


alter table user_table
    add constraint FK7y25bso678qj1wo9ebb85pab3
        foreign key (location_id)
            references location